Origin/header
Olga-Dames/teamProject17 pull request #11
Opened 2022-12-16 08:30 UTC by RomanVoz

На проверку

2022-12-16 22:11 UTC, Olga-Dames requested changes

2022-12-16 22:11 UTC, Olga-Dames commented on src/sass/components/header/_header.scss
> +.icon_arrow {
увидела стрелочку для кнопки, но все же попробуй ее отцентровать...display: flex;
    align-items: center; Я проверила в девтулзах

2022-12-16 22:11 UTC, Olga-Dames commented on src/sass/components/header/_header.scss
> +.header {
подверь пожалучта вертикальные падинги для хедера по всем экранам

2022-12-16 22:11 UTC, Olga-Dames commented on src/sass/components/header/_mobile-menu.scss
> +.mobile-menu .link {
а здесь посмотри по макету, есть стили состояний

2022-12-16 22:11 UTC, Olga-Dames commented on src/sass/components/header/_mobile-menu.scss
> +.menu-container {
Не вижу в мобильном меню кнопки и лого

2022-12-16 22:14 UTC, Olga-Dames commented
Уже поздно, по коду не нашла, пишу здесь)
в планшетном меню нет лого и оно должно быть резиновым по вертикали, сжиматься при уменьшении экрана.
а также, вертикальные паддинги в десктопном хедере не 16px

2022-12-17 15:05 UTC, RomanVoz commented on src/sass/components/header/_header.scss
> +.icon_arrow {
у меня она не центруется. я уже пробовал https://prnt.sc/vfZFLKSR2-EY

2022-12-17 20:23 UTC, merged